name: Hardverapró Scraper

on:
  schedule:
    # 8 óránként fut, de eltolva a kerek időpontról (37. percben)
    - cron: '37 */8 * * *'
  workflow_dispatch: # Kézi indítás is marad

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Függőségek
        run: pip install requests beautifulsoup4 cloudscraper

      - name: Scrapelés
        # Először várunk véletlenszerűen 0-5 percet, csak utána indul a python
        run: |
          # Csak akkor várunk, ha az ütemező (cron) indította el a programot
          if [ "${{ github.event_name }}" = "schedule" ]; then
            WAIT_TIME=$((RANDOM % 300))
            echo "⏰ Ütemezett futás: $WAIT_TIME másodperc várakozás a botvédelem miatt..."
            sleep $WAIT_TIME
          else
            echo "🚀 Manuális indítás: Várakozás kihagyása, azonnali kezdés!"
          fi
          
          # A -u kapcsoló miatt a print() parancsok azonnal látszódni fognak a konzolon!
          python -u scraper.py
          #sleep $((RANDOM % 300))
          #python -u scraper.py

      - name: Commit & Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add hirdetesek.json
          git diff --staged --quiet || git commit -m "Auto: hirdetések frissítve"
          git push
